[phases.setup]
nixPkgs = [
  "python311", 
  "python311Packages.pip", 
  "python311Packages.setuptools",
  "stdenv.cc",
  "cmake",
  "pkg-config"
]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel",
  ". /opt/venv/bin/activate && pip install numpy cython",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]
